### ISSUE TITLE
参考文献

### ISSUE THREAD

**Issue by tianxuzhang** [xswei/PC_Edge_Bundling#1]
nice work!
呆子，有没有相关文献啊？

**Comment by xswei** [comment]
这个算法的论文预计7月份发表出来
其他类似的文献
1. Evaluation of a Bundling Technique for Parallel Coordinates
2. An Edge-Bundling Layout for Interactive Parallel Coordinates
3. Illustrative parallel coordinates
4. Visual Clustering in Parallel Coordinates
